@startsalt
{+
  {* <b>AI Models Comparator | Models | Ranking | News | Log in }
  .
  <b>Models
  .
  {#
    <&image> <b>Anthropic | <&image> <b>Google | <&image> <b>Meta
    Claude Opus | Gemini Flash | Llama 3.3
    Claude Sonnet | Gemini Pro | Llama 4
    <&image> <b>Mistral | <&image> <b>OpenAI | <&image> <b>xAI
    Codestral | GPT-4o | Grok 3
    Mistral Large | GPT-5 | Grok 4
  }
}
@endsalt
